Updated README docs for terraform modules
AnswerConsulting/AnswerKing-Infrastructure pull request #10
Opened 2023-01-27 16:57 UTC by JoeCSykes

2023-01-30 10:25 UTC, bethcryer commented on Terraform_modules/ec2_instance/README.md
> +This vaule indicates whether changes to the `user_data` value triggers a rebuild of the EC2 instance. The default value is `true`.
*value

2023-01-30 12:08 UTC, bethcryer requested changes
only issue I saw were typos, otherwise the readme looks super comprehensive 👍

2023-01-30 12:08 UTC, bethcryer commented on Terraform_modules/ec2_instance/README.md
> +This is the type of EC2 instane you want (e.g. "t2.micro", "m5.large" etc.). The default value for this is "t2.micro" as this is the free tier instance.
*instance

2023-01-30 12:08 UTC, bethcryer commented on Terraform_modules/ec2_instance/README.md
> +This Terraform module will produce an EC2 instance which can be accessed via ssh or session manager via the aws management console. It also allows the posibility
*possibility

2023-01-30 12:08 UTC, bethcryer commented on Terraform_modules/rds_serverless_cluster/README.md
> +**project_name (Manadatory)**
*Mandatory

2023-02-01 09:08 UTC, JoeCSykes commented on Terraform_modules/ec2_instance/README.md
> +This vaule indicates whether changes to the `user_data` value triggers a rebuild of the EC2 instance. The default value is `true`.
Done

2023-02-01 09:08 UTC, JoeCSykes commented on Terraform_modules/ec2_instance/README.md
> +This is the type of EC2 instane you want (e.g. "t2.micro", "m5.large" etc.). The default value for this is "t2.micro" as this is the free tier instance.
Done

2023-02-01 09:08 UTC, JoeCSykes commented on Terraform_modules/ec2_instance/README.md
> +This Terraform module will produce an EC2 instance which can be accessed via ssh or session manager via the aws management console. It also allows the posibility
Done

2023-02-01 09:10 UTC, JoeCSykes commented on Terraform_modules/rds_serverless_cluster/README.md
> +**project_name (Manadatory)**
Done

2023-02-01 10:10 UTC, bethcryer approved these changes

2023-02-01 10:42 UTC, merged