Enable Storage Encryption by default
AnswerConsulting/AnswerKing-Infrastructure pull request #27
Opened 2023-02-13 16:08 UTC by robg-answer

2023-02-13 18:18 UTC, cmbuckley approved these changes

2023-02-14 08:46 UTC, chrisbloe requested changes

2023-02-14 08:46 UTC, chrisbloe commented on Terraform_modules/rds_serverless_cluster/variables.tf
> +  default     = 1
There is a limit on the values allowed - there should be some validation added... https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#backup_retention_period

2023-02-14 10:24 UTC, cmbuckley commented on Terraform_modules/rds_serverless_cluster/variables.tf
> +    error_message = "The maximum retention period that can be set is 35"
This will error because the error message needs to be a sentence apparently - just add a full stop at the end and it'll be fine

2023-02-14 10:32 UTC, cmbuckley commented on Terraform_modules/rds_serverless_cluster/variables.tf
> +    error_message = "The maximum retention period that can be set is 35"
```suggestion
    error_message = "The maximum retention period that can be set is 35."
```

2023-02-15 11:39 UTC, merged